// MESSAGE RADIO PACKING
package com.MAVLink.Messages.ardupilotmega;

import java.util.List;

import com.MAVLink.Messages.MAVLinkMessage;

/**
* Status generated by radio
*/
public class msg_radio extends MAVLinkMessage{

	public static final int MAVLINK_MSG_ID_RADIO = 166;
	public static final int MAVLINK_MSG_LENGTH = 9;

 	/**
	*receive errors
	*/
	public short rxerrors; 
 	/**
	*count of error corrected packets
	*/
	public short fixed; 
 	/**
	*local signal strength
	*/
	public byte rssi; 
 	/**
	*remote signal strength
	*/
	public byte remrssi; 
 	/**
	*how full the tx buffer is as a percentage
	*/
	public byte txbuf; 
 	/**
	*background noise level
	*/
	public byte noise; 
 	/**
	*remote background noise level
	*/
	public byte remnoise; 

/**
 * Decode a radio message into this class fields
 *
 * @param payload The message to decode
 */
public static MAVLinkMessage unpack(List<Integer> payload) {
    msg_radio m = new msg_radio();
	//m.rxerrors = _get_rxerrors(msg);
	//m.fixed = _get_fixed(msg);
	//m.rssi = _get_rssi(msg);
	//m.remrssi = _get_remrssi(msg);
	//m.txbuf = _get_txbuf(msg);
	//m.noise = _get_noise(msg);
	//m.remnoise = _get_remnoise(msg);
    return m;	

    }
}
